apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  #how to find the pods it creates
  selector:
    matchLabels:
      app: orders
  #how to create pods
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: vinaayak/orders
          # Saving secrets in kubernates pods
          env:
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # It will get pod name eg: orders-depl-9676bfb-tsjs5
            - name: DB_URL
              value: "mongodb://orders-mongo-srv:27017/orders"
            - name: HOST_IP
              value: "0.0.0.0"
            - name: HOST_PORT
              value: "3000"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
